### ISSUE TITLE
Move builds from Netlify to Github Actions

### ISSUE THREAD

**Issue by stephencweiss** [stephencweiss/stephencharlesweiss.com#297]
The goal of this is to build regularly from Github using Github actions.

**Comment by stephencweiss** [comment]
@dance2die has a nice demonstration of this: https://github.com/dance2die/SHANc/blob/master/.github/workflows/build-hourly-deploy-to-netlify.yml

**Comment by dance2die** [comment]
Thanks, @stephencweiss :) 

I didn't know you also was running outta [build minutes](https://spectrum.chat/gatsby-js/general/build-time-optimization~78719e84-9cf6-4a6f-bffe-0c92730be7ca) 😄  

The  post doesn't show how to cache packages/builds so will be slower.  
Would you be willing to figure out how? & share? 😉

**Comment by stephencweiss** [comment]
The goal is to replicate the same caching achieved in #285

**Comment by stephencweiss** [comment]
This is complete see - #174
